image: dobrautz/neci_base:hdf5

pipelines:
 default: 
  - step: 
     script: 
      - echo "test this"
      - rm -rf build_docker_test
      - mkdir build_docker_test 
      - cd build_docker_test 
      - cmake ..
      - make -j neci
      - rm -rf * 
      - cd .. 
      - rmdir build_docker_test

 custom:
  test:
   - step:
      script:
      - echo "test manual"
      - rm -rf build_docker_test
      - mkdir build_docker_test 
      - cd build_docker_test 
      - cmake ..
      - make neci
      - rm -rf * 
      - cd .. 
      - rmdir build_docker_test
      - echo "done!"

  test_suite: 
   - step: 
      script: 
       - echo "test to run test_suite:"
       - rm -rf build
       - mkdir build 
       - cd build 
       - cmake .. 
       - make -j
       - cd ../test_suite 
       - testcode.py 
       - echo "the question is does this flag it as succesfull only if it passes??"

  test_suite_single: 
   - step: 
      script: 
       - echo "test to run test_suite:"
       - rm -rf build
       - mkdir build 
       - cd build 
       - cmake .. 
       - make -j neci
       - cd ../test_suite 
         # i have to run mpi as non root.. do some workaround
       - adduser temp
       - su -c "/testcode/bin/testcode.py -c neci/parallel/C_Solid" -s /bin/sh temp
         # - /testcode/bin/testcode.py -c neci/parallel/C_Solid
       - echo "the question is does this flag it as succesfull only if it passes??"

  test_suite_single_serial:
    - step:
       script: 
        - echo "test to run test_suite:"
        - rm -rf build
        - mkdir build 
        - cd build 
        - cmake .. 
        - make -j neci
        - cd ../test_suite 
        - /testcode/bin/testcode.py -c neci/serial/2x2_real_space_hubbard
        - echo "the question is does this flag it as succesfull only if it passes??"

  full_test_suite:
    - step: 
       script:
         # try and run the full test_suite, to see how long it takes.. 
        - rm -rf build 
        - mkdir build 
        - cd build 
        - cmake .. 
        - make -j 
        - cd ../test_suite 
        - adduser temp
        - su -c "/testcode/bin/testcode.py" -s /bin/sh temp 
        - echo "everything passed!"

  debug_build: 
    - step: 
       script: 
        - rm -rf build 
        - mkdir build 
        - cd build 
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j neci mneci kneci kmneci dneci
        - cd ../test_suite
        - adduser temp
        - su -c "/testcode/bin/testcode.py" -s /bin/sh temp
        - echo "debug build + test_suite passed!"


  build_docker_image:
    - step:
       script:
         - docker version
         # i have to figure out how to safely store my credentials in env variables.. 
         #- docker build -t dobrautz/neci_base:testsuite .
         #- docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
         #- docker push dobrautz/neci_base:testsuite

  build_hdf5:
    - step:
       script: 
         # test to build neci + hdf5 (without using a docker image with hdf5.. 
         # caching this hdf5 dependency(since the cache gets deleted every week any way would 
         # be an optimal combination.. 
        - rm -rf build 
        - mkdir build 
        - cd build 
        - cmake -DENABLE_BUILD_HDF5=ON -DENABLE_HDF5=ON ..
        - make -j hdf5 
        - make -j neci 

options:
  docker: true

      
