# i have two more images, which mimick the office setting, prepared now:
image: dobrautz/neci_base:opensuse-leap-15.2

options:
  docker: true


pipelines:
  # default setup: only build neci for all branches and run neci unit tests, do not do any testsuite runs!
  #   to save pipeline minutes
 default:
  - step:
     size: 2x
     script:
      - git submodule update --init
      - rm -rf build
      - mkdir build
      - cd build
      - echo "building release version"
      - cmake ..
      - make -j neci test_neci
      - echo "done building release version"
      - echo "running unit tests"
      - ctest -R test_neci.*
      - echo "unit tests passed"

 branches:
   # for the master branch pushes run the full compilation, unit tests and part of the testsuite
   master:
    - step:
       size: 2x
       script:
        - git submodule update --init
        - rm -rf build
        - mkdir build
        - cd build
        - echo "building release version"
        - cmake ..
        - make -j
        - echo "done building release version"
        - echo "running unit tests"
        - ctest
        - echo "unit tests passed"
        # - echo "running limited test_suite(to save build-minutes)"
        # - useradd temp
        # - cd ../test_suite
        # - su -c "/testcode/bin/testcode.py -c dneci/double_occ/hub_2x2 -c kmneci/Rn_lanczos_fci -c kneci/C_221_int -c mneci/cfqmc/HeHe_5_states -c neci/parallel/C_Solid -vvv" -s /bin/sh temp

   devel:
    - step:
       size: 2x
       script:
        - git submodule update --init
        - rm -rf build
        - mkdir build
        - cd build
        - echo "building release version"
        - cmake ..
        - make -j
        - echo "done building release version"
        - echo "running unit tests"
        - ctest
        - echo "unit tests passed"
        # - echo "running limited test_suite(to save build-minutes)"
        # - useradd temp
        # - cd ../test_suite
        # - su -c "/testcode/bin/testcode.py -c dneci/double_occ/hub_2x2 -c kmneci/Rn_lanczos_fci -c kneci/C_221_int -c mneci/cfqmc/HeHe_5_states -c neci/parallel/C_Solid -vvv" -s /bin/sh temp



 custom:
   # this is an optional full run, if one chooses to test a specific branch fully
  - step:
     size: 2x
     script:
      - git submodule update --init
      - rm -rf build
      - mkdir build
      - cd build
      - echo "building release version"
      - cmake ..
      - make -j
      - echo "done building release version"
      - echo "running unit tests"
      - ctest
      - echo "unit tests passed"
      - echo "running limited test_suite(to save build-minutes)"
      - useradd temp
      - cd ../test_suite
      - su -c "/testcode/bin/testcode.py -c dneci/double_occ/hub_2x2 -c kmneci/Rn_lanczos_fci -c kneci/C_221_int -c mneci/cfqmc/HeHe_5_states -c neci/parallel/C_Solid -vvv" -s /bin/sh temp

