image: dobrautz/neci_base:testsuite

pipelines:
 default: 
  - step: 
     script: 
      - echo "test this"
      - rm -rf build_docker_test
      - mkdir build_docker_test 
      - cd build_docker_test 
      - cmake ..
      - make neci
      - rm -rf * 
      - cd .. 
      - rmdir build_docker_test

 custom:
  test:
   - step:
      script:
      - echo "test manual"
      - rm -rf build_docker_test
      - mkdir build_docker_test 
      - cd build_docker_test 
      - cmake ..
      - make neci
      - rm -rf * 
      - cd .. 
      - rmdir build_docker_test
      - echo "done!"

  test_suite: 
   - step: 
      script: 
       - echo "test to run test_suite:"
       - rm -rf build
       - mkdir build 
       - cd build 
       - cmake .. 
       - make -j
       - cd ../test_suite 
       - testcode.py 
       - echo "the question is does this flag it as succesfull only if it passes??"

  test_suite_single: 
   - step: 
      script: 
       - echo "test to run test_suite:"
       - rm -rf build
       - mkdir build 
       - cd build 
       - cmake .. 
       - make -j neci
       - cd ../test_suite 
       - /testcode/bin/testcode.py -c neci/parallel/C_solid
       - echo "the question is does this flag it as succesfull only if it passes??"


       
