image: dobrautz/neci_base:testsuite

pipelines:
 default: 
  - step: 
     script: 
      - echo "test this"
      - rm -rf build_docker_test
      - mkdir build_docker_test 
      - cd build_docker_test 
      - cmake ..
      - make neci
      - rm -rf * 
      - cd .. 
      - rmdir build_docker_test

 custom:
  test:
   - step:
      script:
      - echo "test manual"
      - rm -rf build_docker_test
      - mkdir build_docker_test 
      - cd build_docker_test 
      - cmake ..
      - make neci
      - rm -rf * 
      - cd .. 
      - rmdir build_docker_test
      - echo "done!"

  test_suite: 
   - step: 
      script: 
       - echo "test to run test_suite:"
       - rm -rf build
       - mkdir build 
       - cd build 
       - cmake .. 
       - make -j
       - cd ../test_suite 
       - testcode.py 
       - echo "the question is does this flag it as succesfull only if it passes??"

  test_suite_single: 
   - step: 
      script: 
       - echo "test to run test_suite:"
       - rm -rf build
       - mkdir build 
       - cd build 
       - cmake .. 
       - make -j neci
       - cd ../test_suite 
         # i have to run mpi as non root.. do some workaround
       - adduser temp
       - su -c "/testcode/bin/testcode.py -c neci/parallel/C_Solid" -s /bin/sh temp
         # - /testcode/bin/testcode.py -c neci/parallel/C_Solid
       - echo "the question is does this flag it as succesfull only if it passes??"

  test_suite_single_serial:
    - step:
       script: 
        - echo "test to run test_suite:"
        - rm -rf build
        - mkdir build 
        - cd build 
        - cmake .. 
        - make -j neci
        - cd ../test_suite 
        - /testcode/bin/testcode.py -c neci/serial/2x2_real_space_hubbard
        - echo "the question is does this flag it as succesfull only if it passes??"

  full_test_suite:
    - step: 
       script:
         # try and run the full test_suite, to see how long it takes.. 
        - rm -rf build 
        - mkdir build 
        - cd build 
        - cmake .. 
        - make -j 
        - cd ../test_suite 
        - adduser temp
        - su -c "/testcode/bin/testcode.py" -s /bin/sh temp 
        - echo "everything passed!"

  debug_build: 
    - step: 
       script: 
        - rm -rf build 
        - mkdir build 
        - cd build 
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j 
        - cd ../test_suite
        - adduser temp
        - su -c "/testcode/bin/testcode.py" -s /bin/sh temp
        - echo "debug build + test_suite passed!"


      
